variables:
  POSTGRES_DB: "EPMT"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "example"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip

services:
  - postgres:latest


build:python3:
  image: rockylinux:8
  script:
    - yum update -y
    - yum install -y findutils unzip bash tcsh nc curl make git gcc postgresql-devel zlib-devel bzip2 bzip2-devel readline-devel sqlite-devel openssl-devel xz xz-devel libffi-devel

    - dnf module install python39 -y
    - dnf install -y python39-devel
    - alternatives --set python3 /usr/bin/python3.9

    - python3 -V
    - python3 -m pip install --upgrade pip

    - yum install -y gcc-c++
    
    - pip3 install -r requirements.txt.py3

    - make epmt-dash
    - make OUTSIDE_DOCKER="YUP" papiex-dist
    - make dist python-dist dist-test

    - pip3 install src/dist/epmt*gz
    - SITE_PACKAGES=$(python3 -c "import site; print(site.getsitepackages()[0])")
    - mkdir -p ${SITE_PACKAGES}/papiex-epmt-install
    - ln -s  ${SITE_PACKAGES}/epmt/lib ${SITE_PACKAGES}/papiex-epmt-install/
    - ln -s  ${SITE_PACKAGES}/epmt/bin ${SITE_PACKAGES}/papiex-epmt-install/

    - export PATH='/usr/bin:${PATH}:/usr/local/bin:/usr/local/libexec'

    - epmt -v -V && echo "success! :-)" || echo "fail! but keep going..."

    - epmt -v check && echo "success! :-)" || echo "fail! but keep going..."

    - pip install pytest || echo "tried to install pytest but failed. keep going!"

#	# this takes A LONG TIME!
#    - epmt -v -V && echo "success! :-)" || echo "fail! but keep going..."    - epmt integration && echo "success! :-)" || echo "fail! but keep going..."






