#!/bin/sh

epmt -v -V
epmt -vv check

TZ=UTC pytest -x -vv src/epmt/test/test_anysh.py
TZ=UTC pytest -x -vv src/epmt/test/test_cmds.py
TZ=UTC pytest -x -vv src/epmt/test/test_db_migration.py
TZ=UTC pytest -x -vv src/epmt/test/test_db_schema.py
TZ=UTC pytest -x -vv src/epmt/test/test_explore.py
TZ=UTC pytest -x -vv src/epmt/test/test_lib.py
TZ=UTC pytest -x -vv src/epmt/test/test_outliers.py
TZ=UTC pytest -x -vv src/epmt/test/test_query.py
TZ=UTC pytest -x -vv src/epmt/test/test_run.py
TZ=UTC pytest -x -vv src/epmt/test/test_settings.py
TZ=UTC pytest -x -vv src/epmt/test/test_shell.py
TZ=UTC pytest -x -vv src/epmt/test/test_stat.py
TZ=UTC pytest -x -vv src/epmt/test/test_submit.py

#python3 -m unittest -v epmt.test.test_anysh
#python3 -m unittest -v epmt.test.test_cmds
#python3 -m unittest -v epmt.test.test_db_migration
#python3 -m unittest -v epmt.test.test_db_schema
#python3 -m unittest -v epmt.test.test_explore
#python3 -m unittest -v epmt.test.test_lib
#python3 -m unittest -v epmt.test.test_outliers
#python3 -m unittest -v epmt.test.test_query
#python3 -m unittest -v epmt.test.test_run
#python3 -m unittest -v epmt.test.test_settings
#python3 -m unittest -v epmt.test.test_shell
#python3 -m unittest -v epmt.test.test_stat
#python3 -m unittest -v epmt.test.test_submit

#epmt integration

#pylint --rcfile pylintrc --fail-under 6.1 --ignore-paths src/epmt/ui src/epmt

#pylint --rcfile pylintrc --fail-under 5.5 src/epmt/ui

#pylint --rcfile pylintrc --fail-under 9.9 src/scripts/epmt

