FROM giovtorres/docker-centos6-slurm:latest

RUN yum update -y
RUN yum install -y tcsh environment-modules
RUN yum clean all
RUN rm -rf /var/cache/yum

WORKDIR /tmp
ARG install_path=/opt/minimalmetrics
ARG epmt_version
ARG epmt_full_release

WORKDIR ${install_path}
COPY ${epmt_full_release} .
COPY utils/epmt-installer .
RUN echo -ne "\n\n" | ./epmt-installer `basename ${epmt_full_release}`
ENV PATH="${install_path}/epmt-${epmt_version}/epmt-install/epmt:${PATH}"
RUN rm -f *.tgz epmt-installer

CMD ["/bin/bash", "-c", "epmt check; epmt unittest; pytest -x -vv $(python3 -c 'from epmt.epmtlib import get_install_root; print(get_install_root())')/test/integration/test_integration_*.py"]
