## this works for podman, but not for docker
#FROM localhost/slurm-cluster:25.05.3

# this works for docker but not for podman
# built locally from giovtorres/slurm-docker-cluster tag 0.9.0 (Rocky Linux 8)
FROM docker.io/library/slurm-cluster:25.05.3

# the image on dockerhub in actually centOS7 based, despite what the
# dockerfile for the image says
#FROM giovtorres/docker-slurm-cluster:latest

RUN yum update -y
RUN yum install -y \
    tcsh \
    environment-modules
RUN yum install -y \
    unzip \
    bash \
    tcsh \
    nc \
    curl \
    make \
    git \
    gcc \
    postgresql-devel \
    zlib-devel \
    bzip2 \
    bzip2-devel \
    readline-devel \
    sqlite-devel \
    openssl-devel \
    xz \
    xz-devel \
    libffi-devel

ARG sqlite_year
ARG sqlite_version
ARG python_version

# Install Python 3.9 and SQLite from system packages instead of building from source
RUN rm -rf /usr/local/bin/python* /usr/local/lib/*python*
RUN dnf module install python39 -y \
    && dnf install -y python39-devel \
    && alternatives --set python3 /usr/bin/python3.9

RUN python3 -V
RUN python3 -m pip install --upgrade pip

RUN yum install -y gcc-c++

COPY requirements.txt.py3 /tmp/
RUN pip3 install -r /tmp/requirements.txt.py3

COPY src/epmt/ui/requirements-ui.txt.py3 /tmp
# RUN pip3 install -r /tmp/requirements-ui.txt.py3

RUN rm -f /tmp/requirements.txt.py3 /tmp/requirements-ui.txt.py3
RUN yum clean all
RUN rm -rf /var/cache/yum

ARG install_path
ARG epmt_version
ARG epmt_full_release
ARG epmt_python_full_release

WORKDIR ${install_path}_archive
COPY ${epmt_full_release} .
COPY src/dist/${epmt_python_full_release} .


RUN python3 -m pip install ${epmt_python_full_release}

RUN SITE_PACKAGES=$(python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))") \
    && tar zxf ${epmt_python_full_release} \
    && mv epmt-${epmt_version}/papiex-epmt-install ${SITE_PACKAGES}/
#    && rm -rf *.tgz
COPY utils/epmt-installer .

WORKDIR ${install_path}
RUN ls ${install_path}

RUN echo -ne "\n\n" | ${install_path}_archive/epmt-installer ${install_path}_archive/EPMT*tgz
RUN rm -f *.tgz epmt-installer

ENV PATH="/usr/bin:${PATH}:/usr/local/bin:/usr/local/libexec"

RUN pip3 install pytest



