FROM rockylinux:8

RUN yum update -y
RUN yum install -y \
	unzip \
	bash \
	tcsh \
	nc \
    curl \
    make \
    git \
    gcc \
    postgresql-devel \
    zlib-devel \
    bzip2 \
    bzip2-devel \
    readline-devel \
    sqlite-devel \
    openssl-devel \
    xz \
    xz-devel \
    libffi-devel

ARG sqlite_year
ARG sqlite_version
ARG python_version

# Install Python 3.9 and SQLite from system packages instead of building from source
RUN dnf module install python39 -y \
    && dnf install -y python39-devel \
    && alternatives --set python3 /usr/bin/python3.9

RUN python3 -V
RUN python3 -m pip install --upgrade pip

RUN yum install -y gcc-c++

COPY requirements.txt.py3 /tmp/
RUN pip3 install -r /tmp/requirements.txt.py3

COPY src/epmt/ui/requirements-ui.txt.py3 /tmp
# RUN pip3 install -r /tmp/requirements-ui.txt.py3

RUN rm -f /tmp/requirements.txt.py3 /tmp/requirements-ui.txt.py3
RUN yum clean all
RUN rm -rf /usr/src /var/cache/yum

