site_name: Experiment Performance Management Tool (EPMT)
theme:
  name: readthedocs
  navigation_depth: 2

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

use_directory_urls: false

nav:
  - EPMT Quick Start: Quickstart.md
  - EPMT Install: INSTALL.md
  - EPMT Readme: README.md
  - Developer Guide: DEVELOPER.md
  - EPMT Explore Command: epmt-explore-cli.md
  - EPMT Commands: epmt_cmds.md
  - Migrations: migrations.md
  - Multiple DB Users: db-multiple-users.md
  - Metrics: metrics.md
  - License: LICENSE.md
  - Release Notes: RELEASE_NOTES.md
