name: build_conda

on:
  pull_request:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"] # , "3.10", "3.11"]
      fail-fast: false  # let all versions run even if one fails

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up base Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: true
          python-version: ${{ matrix.python-version }}

      - name: Configure conda channels
        run: |
          echo "removing conda default channels, appending open-source ones"
          conda config --append channels conda-forge
          conda config --append channels noaa-gfdl

          echo "setting strict channel priority"
          conda config --set channel_priority strict

          echo "setting anaconda_upload to no"
          conda config --set anaconda_upload no

          echo "printing conda config just in case"
          conda config --show

      - name: Install conda-build
        run: |
          conda install -y conda-build

      - name: Verify conda-build is available
        run: |
          conda build --version

      - name: Build epmt conda package
        run: |
          conda build .
