name: markdown lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4

      - name: Lint markdown files
        continue-on-error: true
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: |
            epmtdocs/docs/**/*.md
            *.md
